<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<AssemblyName>ThirdPersonMod</AssemblyName>
		<Description>相机补丁</Description>
		<Version>1.0.0</Version>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<LangVersion>latest</LangVersion>
		<OutputType>Library</OutputType>
		<AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
		<GenerateBindingRedirectsOutputType>false</GenerateBindingRedirectsOutputType>
	</PropertyGroup>

	<ItemGroup>
		<!-- BepInEx 插件核心引用 -->
		<Reference Include="BepInEx">
			<HintPath>libs\BepInEx.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="0Harmony">
			<HintPath>libs\0Harmony.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="Assembly-CSharp">
			<HintPath>libs\Assembly-CSharp.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="UnityEngine">
			<HintPath>libs\UnityEngine.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>libs\UnityEngine.CoreModule.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="UnityEngine.InputLegacyModule">
			<HintPath>libs\UnityEngine.InputLegacyModule.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="Unity.Netcode.Runtime">
			<HintPath>libs\Unity.Netcode.Runtime.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="Unity.InputSystem">
			<HintPath>libs\Unity.InputSystem.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="UnityEngine.PhysicsModule">
			<HintPath>libs\UnityEngine.PhysicsModule.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="UnityEngine.AnimationModule">
			<HintPath>libs\UnityEngine.AnimationModule.dll</HintPath>
			<Private>False</Private>
		</Reference>
	</ItemGroup>
</Project>
